yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('', views.index,
         name='index'),
    path('group/<slug:slug>/', views.group_posts,
         name='group_posts'),
    path('profile/<str:username>/', views.profile,
         name='profile'),
    path('posts/<int:post_id>/', views.post_detail,
         name='post_detail'),
    path('create/', views.post_create,
         name='post_create'),
    path('posts/<int:post_id>/edit/', views.edit_post,
         name='edit_post'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index,
         name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'

urlpatterns = [
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
]
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()
LETTERS_FOR_POST = 15


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, db_index=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Your post')
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Date')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        help_text='Группа, к которой будет относиться пост',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='groups',
        verbose_name='Группа',
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text[:LETTERS_FOR_POST]

    class Meta:
        ordering = ['-pub_date']


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='author',
    )

    text = models.TextField(
        max_length=200,
    )

    created = models.DateTimeField(
        verbose_name='Дата коммента',
        auto_now_add=True,
    )

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=('user', 'author',),
                name='уникальный фолловер'), ]

    def __str__(self):
        return self.user

yatube/posts/forms.py
from .models import Post, Comment
from django import forms


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {'text': 'Write text', 'group': 'Choose group',
                  'image': 'Choose image'}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': 'Write your comment, please :)'}

yatube/posts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Group, Post, User, Follow
from .forms import PostForm, CommentForm
from posts.utils import paginate
from django.contrib.auth.decorators import login_required

PAGE_FOR_LIST = 10
LETTERS_FOR_POST = 30


def index(request):
    post_list = Post.objects.all()
    page_obj = paginate(request, post_list, PAGE_FOR_LIST)
    context = {
        'page_obj': page_obj, }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.groups.all()
    page_obj = paginate(request, posts, PAGE_FOR_LIST)
    context = {
        'group': group,
        'page_obj': page_obj, }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    title = 'Профайл пользователя'
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    count_posts = posts.count()
    page_obj = paginate(request, posts, PAGE_FOR_LIST)
    status_of_client = request.user.is_authenticated
    request_for_follow = status_of_client and Follow.objects.filter(
        user=request.user,
        author=author).exists()
    context = {
        'following': request_for_follow,
        'author': author,
        'count_posts': count_posts,
        'page_obj': page_obj,
        'title': title, }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    all_posts = post.author.posts
    count = all_posts.count()
    short_post = post.text[:LETTERS_FOR_POST]
    title = 'Пост'
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'form': form,
        'comments': comments,
        'post': post,
        'count': count,
        'short_post': short_post,
        'title': title, }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', request.user)
    return render(request, 'posts/post_create.html', {'form': form})


@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True, }
    return render(request, 'posts/edit_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    author_posts_following = Post.objects.filter(
        author__following__user=request.user)
    page_obj = paginate(request, author_posts_following, PAGE_FOR_LIST)
    context = {
        'page_obj': page_obj, }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if not Follow.objects.filter(
        user=request.user,
        author=author
    ).exists() and request.user != author:
        Follow.objects.create(
            user=request.user,
            author=get_object_or_404(User, username=username))
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    if Follow.objects.filter(
            user=request.user,
            author=get_object_or_404(User, username=username)).exists():
        Follow.objects.filter(
            user=request.user,
            author=get_object_or_404(User, username=username)).delete()
        return redirect('posts:profile', username)

yatube/templates/posts/edit_post.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Новый пост
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post"  enctype="multipart/form-data" action="
                                      {% if is_edit %}
                                        {% url 'posts:edit_post' post.pk %}
                                      {% else %}
                                        {% url 'posts:post_create'  %}
                                      {% endif %}
                                      ">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:"form-control" }}
                {% if field.help_text %}
                  <small
                     id="{{ field.id_for_label }}-help"
                     class="form-text text-muted"
                  >
                    {{ field.help_text }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %} 
{% load cache %} 
{% block title %}  
<ul><ul><ul><ul><ul><ul>
    <h1>Подписки</h1>
  </ul></ul></ul></ul></ul></ul>
{% endblock %} 
{% block content %} 
{% include 'posts/includes/switcher.html'%} 
  {% for post in page_obj %} 
  <ul> 
    <li> 
      Автор: {{ post.author }} 
    </li> 
    <li> 
      Дата публикации:{{ post.pub_date|date:"d E Y" }} 
    </li> 
  </ul> 
  <p>{{ post.text }}</p> 
  {% include 'posts/includes/img_for_all.html' %}       
  <li>
    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
    </li>
    <li>
    <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
    <li>
    {% if post.group %}    
    <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a> 
    {% endif %}
    </li>    
  {% if not forloop.last %}<hr>{% endif %} 
  {% endfor %} 
   
  {% include 'posts/includes/paginator.html' %} 
 
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block content %}
<ul><ul><ul><ul><ul><ul>
  {% block title %}Записи группы: {{ group.title }}{% endblock %}
  </ul></ul></ul></ul></ul></ul>
<ul><ul><ul><ul><ul><ul>
<h1>{{ group.title }}</h1>
</ul></ul></ul></ul></ul></ul>
<ul><ul><ul><ul><ul><ul>
<p>
  {{ group.description }}
</p>
</ul></ul></ul></ul></ul></ul>
<div class="container py-5"> 
  {% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author}} 
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    <li>
    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
    </li>
    <li>
    <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
  </ul>
  <a>
  <p>{{ post.text }}</p>
  <a/>
    {% include 'posts/includes/img_for_all.html' %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<ul><ul><ul><ul><ul><ul>
  <h1>Последние обновления на сайте</h1>
</ul></ul></ul></ul></ul></ul>
{% include 'posts/includes/switcher.html' %}
<div class="container py-5"> 
  {% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author}} 
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
    <li>
    <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
    </li>
    <li>
    <a href="{% url 'posts:profile' post.author %}">все посты пользователя</a>
    </li>
    <li>
    {% if post.group %}    
    <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a> 
    {% endif %}
    </li>    
  </ul>
  <a>
  <p>{{ post.text }}</p>
  <a/>
    {% include 'posts/includes/img_for_all.html' %}
    {% if not forloop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
  {% if is_edit %}
    Редактировать запись
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать запись
          {% else %}
            Новый пост
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post"  enctype="multipart/form-data" action="
                                      {% if is_edit %}
                                        {% url 'posts:edit_post' post.pk %}
                                      {% else %}
                                        {% url 'posts:post_create'  %}
                                      {% endif %}
                                      ">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:"form-control" }}
                {% if field.help_text %}
                  <small
                     id="{{ field.id_for_label }}-help"
                     class="form-text text-muted"
                  >
                    {{ field.help_text }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Сохранить
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}Пост {{ post.text|slice:":30" }}{% endblock %}
{% load thumbnail %}
{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group.title }}
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author }}
        </li>
        <li class="list-group-item">
          Всего постов автора:  {{ post.author.posts.count }}
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">все посты пользователя</a>
        </li>
        <li class="list-group-item">
        <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
        </li> 
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {{ post.text|linebreaks }}
      {% if request.user == post.author %}
        <a class="btn btn-primary" href="{% url 'posts:edit_post' post.pk %}">
          Редактировать запись
        </a>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
      {% endif %}
    </article>
  
    {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}
            <div class="form-group mb-2">
              {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
    {% endif %}

    {% for comment in post.comments.all %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
          <p>{{ comment.created }}</p>
          <p>{{ comment.text }}</p>
        </div>
      </div>
    {% endfor %}

  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ title }} {{ author }} 
{% endblock %}
{% block content %}
<div class="mb-5">
  <h1>Все посты пользователя:{{ post.author }}</h1>
  <h3>Всего постов: {{ count_posts }}</h3>
  {% if author.username != user.username%}
  {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
    <a
      class="btn btn-lg btn-primary"
      href="{% url 'posts:profile_follow' author.username %}" role="button"
    >
      Подписаться
    </a>
  {% endif %}
{% endif %}
</div>
<div class="container py-5">        
  <h1>Все посты пользователя: {{ author }} </h1>
  <h3>Всего постов: {{ count_posts }} </h3>
  <div class="container py-5"> 
    {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author}} 
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
      <li>
      <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
      </li>
      <li>
      {% if post.group %}    
      <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a> 
      {% endif %}
      </li>    
    </ul>
    <a>
    <p>{{ post.text }}</p>
    <a/>
    {% include 'posts/includes/img_for_all.html' %}     
  {% if not forloop.last %}<hr>{%endif%}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %} 
</div>
{% endblock %}